-- AS 91896 Programming assessment
-- [insert your name here]
-- [give program overview]
-- =============================================================
-- main.lua
-- =============================================================
